### ISSUE TITLE
Use of transition_post_status is problematic with some functions

### ISSUE THREAD

**Issue by CharlyLeetham** [rspraymond/wp-discord#13]
I use Gravity Forms to allow people to edit certain posts from the frontend. That plugin will set an already published post to 'draft' and then republish it. 

As wp-discord uses transition_post_status to determine if a post should be sent to discord is problematic.

To get around this, I've modified the post_published_event function in class-wp-discord-admin.php (Around line 209 at the time of writing) and replaced:

       ` // Only post to discord when a post switches from unpublished to published.
        if ($old_status == 'publish' || $new_status != 'publish') {
            return true;
        }`

With:

        `// Only post to discord when a post switches from unpublished to published.
		$alreadyposted = get_post_meta($post->ID, 'wpdiscord_alreadyposted', true);

        if ( $alreadyposted  ) {
            return true;
        } elseif ($old_status == 'publish' || $new_status != 'publish') {
            return true;
        }`

After 
      `        $webhook->post_content($content);
     `
Add:
     `        update_post_meta($post->ID, 'wpdiscord_alreadyposted', 'true');		
     `

***

These changes allow for custom meta to be set when the discord post is made and then for the post to be skipped if the function in use toggles the published setting.  

I'm sure there's a better way of doing this, but that's what I came up with.

**Comment by rspraymond** [comment]
@CharlyLeetham Did you want to open a pull request for this? Maybe call the boolean wpdiscord_posted

**Comment by rspraymond** [comment]
Also I think it would be fine to just add the condition to the existing if check. 

```php
<?php
// Only post to discord when a post switches from unpublished to published.
    if ($old_status == 'publish' || $new_status != 'publish' || $alreadyposted) {
        return true;
    }`
```

**Comment by CharlyLeetham** [comment]
Hi @rspraymond 
Sorry for the delay, busy few weeks. 
You're correct regarding the logic, I tested that to be sure.
I think I've created the pull request correctly - first time doing this and all.

Please let me know if it's correct.

**Comment by rspraymond** [comment]
@CharlyLeetham Pull request merged. Thanks for your contribution!
